name: Publish package to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write

      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: build
        run: |
          python -m pip install poetry
          poetry install
          poetry build

      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: sign
        uses: sigstore/gh-action-sigstore-python@v2.0.1
        with:
          inputs: ./dist/*.whl ./dist/*.tar.gz
          release-signing-artifacts: true